### ISSUE TITLE
Support rfc 3339

### ISSUE THREAD

**Issue by lpil** [massivefermion/birl#1]
Hello!

RFC 3339 is a much simpler and easier to understand format than ISO 8601, it would be great to support it! Most the time when people say "iso format" they are using the (imo) nicer subset of ISO 8601 that is also RFC 3339.

Cheers,
Louis

**Comment by massivefermion** [comment]
To be honest, I didn't want to get bogged down with the datetime format in the beginning. I wanted to have a working package, and then improve it gradually. I think right now there is enough functionality to make the package useful, so now I can focus on the different formats supported.
