### ISSUE TITLE
time.now() returns BadArg

### ISSUE THREAD

**Issue by finalclass** [massivefermion/birl#10]
When I switch to 0.15.0 then it works fine
However on the recent version I get `Errored(BadArg)`

![image](https://github.com/massivefermion/birl/assets/1343930/2cb2ad70-b59d-4d9d-bf20-4b29e327d300)

![image](https://github.com/massivefermion/birl/assets/1343930/3cc42df2-7c8f-4c41-b8ce-bb954f94afaf)

![image](https://github.com/massivefermion/birl/assets/1343930/399e7680-08c8-41c4-b740-d954a2b4f286)

**Comment by massivefermion** [comment]
Thanks for reporting the issue
What operating system are you on?

**Comment by finalclass** [comment]
I'm on Manjaro linux.

**Comment by massivefermion** [comment]
A new version with the fix has been released
Thanks

**Comment by finalclass** [comment]
Great, thx. I will check this out later today or tomorrow.
