### ISSUE TITLE
Where has from_iso8601 gone?

### ISSUE THREAD

**Issue by lpil** [massivefermion/birl#11]
This function has been removed and there's no changelog saying how to upgrade. What's the new approach?

Thanks,
Louis

**Comment by massivefermion** [comment]
I actually removed it before v1.0 and put a deprecation warning for it. Apparently not enough.
You should use `birl.parse` instead.

**Comment by lpil** [comment]
Fab, thank you. Could you document that function to say what format is accepts please? It has examples but they're not enough to know what the format is.
