### ISSUE TITLE
Erlang monotonic_now/1 function isn't monotonic

### ISSUE THREAD

**Issue by lpil** [massivefermion/birl#2]
Hello!

`monotonic_now/1` is implemented using `os:perf_counter/1`, which isn't monotonic.

You may want to use `erlang:system_info(os_monotonic_time_source).` or  `erlang:monotonic_time/0` depending on what you want. More info there: https://www.erlang.org/doc/apps/erts/time_correction.html

Thanks,
Louis

**Comment by massivefermion** [comment]
I made some changes and I think we can close this issue. And with #3 also probably closed, I'm ready for a new version so that we can move on to other issues. Let me know if I misunderstood something and the code still needs to change regarding this issue.

**Comment by lpil** [comment]
Fab!
