### ISSUE TITLE
Birl appropriate for benchmarking?

### ISSUE THREAD

**Issue by bcpeinhardt** [massivefermion/birl#20]
Hey there!
I'm doing some very basic benchmarking with the following
```gleam
fn time(name: String, f: fn() -> a) -> a {
  let start = birl.now()
  let x = f()
  let end = birl.now()
  let difference = birl.difference(end, start) |> duration.blur_to(duration.MilliSecond)
  io.println(name <> " took: " <> int.to_string(difference) <> "ms")
  x
}
```
which I use like
```gleam
let parallel_freq = time("parallel", fn() { parallel_letter_frequency(workload, 200_000) })
```

My question is
1. Is using Birl for benchmarking this way appropriate and
2. Would a more general timer function be a useful addition?

**Comment by massivefermion** [comment]
Hi
The `Time` type has a `monotonic_time` field which is an option but it exists if the `Time` value is created using e.g. `now`. And when using `difference`, if for both `Time` values the `monotonic_time` field is `Some`, that's the difference you'll get. So what you're doing should be fine!
As for the timer function, do mean something like your `time` function?

**Comment by jrstrunk** [comment]
If you're looking for benchmarking, also try out the Glychee package for Gleam!

**Comment by massivefermion** [comment]
Is this issue concluded? Can I close it?

**Comment by bcpeinhardt** [comment]
Yes!
