### ISSUE TITLE
birl crashing

### ISSUE THREAD

**Issue by schurhammer** [massivefermion/birl#31]
Birl is used by startest and my tests started crashing somewhat randomly. I think it started happening at midnight..

This is a minimal reproduction of the crash
```gleam
  birl.now()
  |> io.debug()
  |> birl.get_offset()
  |> io.debug()
  ```
  ```gleam
  Time(1717157489658988, -129600000000, Some("Pacific/Auckland"), Some(165446))
exception error: #{function => <<"get_offset">>,line => 1206,
                   message => <<"Assertion pattern match failed">>,
                   module => <<"birl">>,
                   value => {error,nil},
                   gleam_error => let_assert}
 ```
 
 Will report back after I sleep to see if anything changes

**Comment by massivefermion** [comment]
Could you give the same output for the js target?

**Comment by mscharley** [comment]
I'm also starting to hit this:

Erlang:
```
Time(1717196983175051, -136800000000, Some("Australia/Melbourne"), Some(198502))
exception error: #{function => <<"get_offset">>,line => 1206,
                   message => <<"Assertion pattern match failed">>,
                   module => <<"birl">>,
                   value => {error,nil},
                   gleam_error => let_assert}
```

Javascript:
```
Time(wall_time: 1717197291396000, offset: 36000000000, timezone: Some("Australia/Melbourne"), monotonic_time: Some(134149))
"+10:00"
```

**Comment by mscharley** [comment]
I suspect this might be related to timezones - it's now after 10am in a +10 timezone and it's now working again.

**Comment by massivefermion** [comment]
Turned out this was happening because the calculations I've been doing on the Erlang target to determine the local offset were not considering an edge case when the month is changing between subsequent days! It should be fixed in the latest version now!
Thanks for the issue
