### ISSUE TITLE
datetime.from_iso does not support ISO 8601 on Erlang

### ISSUE THREAD

**Issue by lpil** [massivefermion/birl#4]
Hello! 

The `from_iso` function does not support ISO 8601. It looks like it supports a subset of RFC 3339 and ISO 8601 but will fail on most ISO 8601 timestamp formats.

Thanks,
Louis

**Comment by massivefermion** [comment]
To be honest, I didn't want to get bogged down with the datetime format in the beginning. I wanted to have a working package, and then improve it gradually. I think right now there is enough functionality to make the package useful, so now I can focus on the different formats supported.
