### ISSUE TITLE
Time + datetime types lack timezone information

### ISSUE THREAD

**Issue by lpil** [massivefermion/birl#5]
Hello!

Currently none of the types of store time zone information, so any time these types of use the programmer will also need to store in another variable the time zone and then adjust for it. This is quite errorprone, I think it would be best to instead have the library handle that's for the programmer.

Thanks,
Louis

**Comment by massivefermion** [comment]
I didn't do it because I want to add a timezone database in the future. Of course js already has that, but as far as I know erlang does not, so we need to have that anyway.
But of course, it makes sense that until we do that, the values at least keep an offset.
